config/routes.rb
Kings::Application.routes.draw do

  root :to => 'pages#home'

  match '/login', :to => 'sessions#new', :as => :login, via: [:get]
  match '/signout', :to => 'sessions#destroy', :as => :sign_out, via: [:get, :post]

  match '/galleries/index2', :to => 'galleries#index2', :as => :index2_gallery, via: [:get]
  match '/galleries/engagement', :to => 'galleries#engagement', :as => :engagement, via: [:get]
  match '/galleries/travel', :to => 'galleries#travel_images', :as => :travel_images, via: [:get]
  match '/galleries/wedding', :to => 'galleries#wedding', :as => :wedding, via: [:get]

  match '/galleries/manage', :to => 'galleries#manage', :as => :manage_gallery, via: [:get, :post]
  match '/galleries/list', :to => 'galleries#list', :as => :list_gallery, via: [:get, :post]
  post  '/galleries/wedding_photos', :to => 'comments#create_gallery_comment', :as => :create_gallery_comment, via: [:get, :post]
  post  '/travels/:id', :to => 'comments#create_travel_comment', :as => :create_travel_comment, via: [:get, :post]
  post  '/foods/:id', :to => 'comments#create_food_comment', :as => :create_food_comment, via: [:get, :post]

  match '/users/manage', :to => 'users#manage', :as => :manage_user, via: [:get, :post]
  match '/users/list', :to => 'users#list', :as => :list_user, via: [:get, :post]
  
  match '/travels/manage', :to => 'travels#manage', :as => :manage_travel, via: [:get, :post]
  match '/travels/list', :to => 'travels#list', :as => :list_travel_blogs, via: [:get, :post]

  match '/foods/manage', :to => 'foods#manage', :as => :manage_food, via: [:get, :post]
  match '/foods/list', :to => 'foods#list', :as => :list_food_blogs, via: [:get, :post]

  match '/quotes/manage', :to => 'quotes#manage', :as => :manage_quote, via: [:get, :post]
  match '/quotes/list', :to => 'quotes#list', :as => :list_quotes, via: [:get, :post]
  
  resources :galleries, :sessions, :users, :admins, :comments, :travels, :foods, :quotes
  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  before_filter :authenticate_admin

  def manage
    @quote = Quote.new if @quote.nil?
    @quote = Quote.find(params[:id]) if params[:id]
  end
  
  def list
    @search = Quote.ransack(params[:search])
    @quotes = @search.result.paginate(page: params[:page], per_page: params[10])
  end
  
  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to(:action => 'list')
    else
      render "manage"
    end
  end
  
  def update
    @quote = Quote.find(params[:id])
    if @quote.update_attributes(quote_params)
      redirect_to(:action => 'list')
    else
      render "manage"
    end    
  end
  
  def destroy
    Quote.find(params[:id]).destroy
    redirect_to :action => 'list'
  end
  
  private 
  
  def quote_params
    params.require(:quote).permit(
    :quote, 
    :author, 
    :travel,
    :food 
    )
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/list.html.erb
<h4>List of Quotes</h4></br>

<div class="display-inline">
  <%= link_to "«« Back to Admin »»", admins_path %>

  <div>
    <%= search_form_for @search, :url => list_quotes_path do |f| %>
      Keyword Search: <%= f.search_field :author_or_quote_cont, :label => false %>
      SORT BY: <%= f.sort_link :id, "ID Order" %>
    <% end %>
  </div>
</div>

<table class="table zebra-striped">
  <thead>
    <tr>
      <th>ID #</th>
      <th>Quote</th>
      <th>Author</th>
      <th>Type</th>      
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |q| %>
    <tr>
      <td><%= q.id %></td>
      <td><%= truncate(q.quote, :length => 50, :separator => " ") %></td>
      <td><%= q.author %></td>
      <td>
        <% if q.travel %>
          Travel
        <% elsif q.food %>
          Food
        <% else %>
        <% end %>
      </td>
      <td><%= link_to "Edit", :action => 'manage', :id => q.id %> | <%= link_to "Delete", q, :method => :delete %></td>        
     </tr>
    <% end %>
  </tbody>  

</table>

<div class="pull-right"><%= will_paginate @quotes, renderer: BootstrapPagination::Rails %></div>    


<div class="btn primary white-link pull-right"><%= link_to "New", :action => 'manage' %></div>

app/views/quotes/manage.html.erb
<%= simple_form_for(@quote, :html => {:class => "form-horizontal"}) do |f| %>

  <%= f.input :author %>
  <%= f.input :quote, :input_html => { style: 'height:200px;', :class => "input-xxlarge" } %>
  <%= f.input :travel, :label => "Travel Quote?", :as => :radio_buttons, :collection => [["True", true], ["False", false]] %>
  <%= f.input :food, :label => "Food Quote?", :as => :radio_buttons, :collection => [["True", true], ["False", false]] %>
  
  <br> 
  
  <div class="pull-right">
    <div class="btn primary white-link"><%= link_to "Cancel", list_travel_blogs_path %></div>
    <%= f.button :submit, :class => "primary" %>
  </div>  
<% end %>