config/routes.rb
Kings::Application.routes.draw do

  root :to => 'pages#home'

  match '/login', :to => 'sessions#new', :as => :login, via: [:get]
  match '/signout', :to => 'sessions#destroy', :as => :sign_out, via: [:get, :post]

  match '/galleries/index2', :to => 'galleries#index2', :as => :index2_gallery, via: [:get]
  match '/galleries/engagement', :to => 'galleries#engagement', :as => :engagement, via: [:get]
  match '/galleries/travel', :to => 'galleries#travel_images', :as => :travel_images, via: [:get]
  match '/galleries/wedding', :to => 'galleries#wedding', :as => :wedding, via: [:get]

  match '/galleries/manage', :to => 'galleries#manage', :as => :manage_gallery, via: [:get, :post]
  match '/galleries/list', :to => 'galleries#list', :as => :list_gallery, via: [:get, :post]
  post  '/galleries/wedding_photos', :to => 'comments#create_gallery_comment', :as => :create_gallery_comment, via: [:get, :post]
  post  '/travels/:id', :to => 'comments#create_travel_comment', :as => :create_travel_comment, via: [:get, :post]
  post  '/foods/:id', :to => 'comments#create_food_comment', :as => :create_food_comment, via: [:get, :post]

  match '/users/manage', :to => 'users#manage', :as => :manage_user, via: [:get, :post]
  match '/users/list', :to => 'users#list', :as => :list_user, via: [:get, :post]
  
  match '/travels/manage', :to => 'travels#manage', :as => :manage_travel, via: [:get, :post]
  match '/travels/list', :to => 'travels#list', :as => :list_travel_blogs, via: [:get, :post]

  match '/foods/manage', :to => 'foods#manage', :as => :manage_food, via: [:get, :post]
  match '/foods/list', :to => 'foods#list', :as => :list_food_blogs, via: [:get, :post]

  match '/quotes/manage', :to => 'quotes#manage', :as => :manage_quote, via: [:get, :post]
  match '/quotes/list', :to => 'quotes#list', :as => :list_quotes, via: [:get, :post]
  
  resources :galleries, :sessions, :users, :admins, :comments, :travels, :foods, :quotes
  

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor   :password
  # attr_accessible :name, :email, :password, :admin, :attending, :image

  has_many :travels
  has_many :foods
  has_many :comments
  
  mount_uploader :image, UserImageUploader
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,                   :presence => true,
                                      :uniqueness => { :case_sensitive => false },
                                      :format => { :with => email_regex },
                                      :on => :create
  
  before_save :encrypt_password, :unless => "password.blank?"
  
  def has_password?(submitted_password)
    password_hash == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    (user && user.has_password?(submitted_password)) ? user : nil
  end
    
  def self.authenticate_with_password_salt(id, cookie_password_salt)
    user = find_by_id(id)
    (user && user.password_salt == cookie_password_salt) ? user : nil
  end
  
  def before_update
  	if !password.blank?
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end
  
  private
  
    def encrypt_password
      self.password_salt = make_password_salt unless has_password?(password)
      self.password_hash = encrypt(password)
    end
    
    def encrypt(string)
      secure_password_hash("#{password_salt}--#{string}")
    end
    
    def make_password_salt
      secure_password_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_password_hash(string)
      Digest::SHA2.hexdigest(string)
    end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_admin
  
  def list
    @search = User.ransack(params[:search])
    @users = @search.result.paginate(page: params[:page], per_page: params[12])
  end
  
  def new
    @user = User.new if @user.nil?
  end
  
  def edit
    @user = User.find(params[:id]) if params[:id]
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :action => 'list'
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to :action => 'list'
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to :action => 'list'
  end
  
  private
  
  def user_params
    params.require(:user).permit(
    :name, 
    :email, 
    :password, 
    :admin, 
    :attending, 
    :image
    )
  end
  


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= f.input :name %>
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :attending, :as => :select %>

app/views/users/edit.html.erb
<h2><%= @page_title = "Editing User"%></h2>


<%= simple_form_for @user, :html => {:multipart => true} do |f| %>
    <div class="span3">
      <%= image_tag(@user.image_url(:thumb)) if @user.image %>
      <%= f.input :image, :label => "Photo", :as => :file %>
    </div>
  <div class="span6">
    <%= render(:partial => 'form', :locals => {:f => f})%>    
    <%= f.button :submit, 'Submit', :class => "primary" %>
  </div>
  
<% end %>

app/views/users/list.html.erb
<h4>List of Users</h4></br>

<div class="display-inline">
  <%= link_to "«« Back to Admin »»", admins_path %>

  <div>
    <%= simple_form_for @search, :url => list_user_path do |f| %>
      Keyword search: <%= f.input :name_contains, :label => false %>
      SORT BY: <%= f.sort_link :id, "ID Order" %> | <%= f.sort_link :name, "Name" %> | <%= f.sort_link :lastlogin, "Last Logged In" %>
    <% end %>
  </div>
</div>

<table class="table zebra-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>ID #</th>
      <th>Name</th>
      <th>Email</th>
      <th>Last Login</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag(user.image_url(:thumb), :class => "round-images") if user.image %></td>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.lastlogin.strftime("%b %d, %Y") if user.lastlogin %></td>
      <td><%= link_to "Edit", edit_user_path(user), :id => user.id %> | <%= link_to "Delete", user, :method => :delete %></td>        
     </tr>
    <% end %>
  </tbody>  

</table>

<div class="pull-right"><%= will_paginate @users, renderer: BootstrapPagination::Rails %></div>    


<div class="btn primary white-link pull-right"><%= link_to "New", :action => 'new' %></div>

app/views/users/new.html.erb
<h2><%= @page_title = "Creating User"%></h2>


<%= simple_form_for @user, :html => {:multipart => true} do |f| %>
    <div class="span3">
      <%= image_tag(@user.image_url(:thumb)) if @user.image %>
      <%= f.input :image, :label => "Photo", :as => :file %>
    </div>
  <div class="span6">
    <%= render(:partial => 'form', :locals => {:f => f})%>    
    <%= f.button :submit, 'Submit', :class => "primary" %>
  </div>
  
<% end %>