config/routes.rb
Kings::Application.routes.draw do

  root :to => 'pages#home'

  match '/login', :to => 'sessions#new', :as => :login, via: [:get]
  match '/signout', :to => 'sessions#destroy', :as => :sign_out, via: [:get, :post]

  match '/galleries/index2', :to => 'galleries#index2', :as => :index2_gallery, via: [:get]
  match '/galleries/engagement', :to => 'galleries#engagement', :as => :engagement, via: [:get]
  match '/galleries/travel', :to => 'galleries#travel_images', :as => :travel_images, via: [:get]
  match '/galleries/wedding', :to => 'galleries#wedding', :as => :wedding, via: [:get]

  match '/galleries/manage', :to => 'galleries#manage', :as => :manage_gallery, via: [:get, :post]
  match '/galleries/list', :to => 'galleries#list', :as => :list_gallery, via: [:get, :post]
  post  '/galleries/wedding_photos', :to => 'comments#create_gallery_comment', :as => :create_gallery_comment, via: [:get, :post]
  post  '/travels/:id', :to => 'comments#create_travel_comment', :as => :create_travel_comment, via: [:get, :post]
  post  '/foods/:id', :to => 'comments#create_food_comment', :as => :create_food_comment, via: [:get, :post]

  match '/users/manage', :to => 'users#manage', :as => :manage_user, via: [:get, :post]
  match '/users/list', :to => 'users#list', :as => :list_user, via: [:get, :post]
  
  match '/travels/manage', :to => 'travels#manage', :as => :manage_travel, via: [:get, :post]
  match '/travels/list', :to => 'travels#list', :as => :list_travel_blogs, via: [:get, :post]

  match '/foods/manage', :to => 'foods#manage', :as => :manage_food, via: [:get, :post]
  match '/foods/list', :to => 'foods#list', :as => :list_food_blogs, via: [:get, :post]

  match '/quotes/manage', :to => 'quotes#manage', :as => :manage_quote, via: [:get, :post]
  match '/quotes/list', :to => 'quotes#list', :as => :list_quotes, via: [:get, :post]
  
  resources :galleries, :sessions, :users, :admins, :comments, :travels, :foods, :quotes
  

end

app/models/food.rb
class Food < ActiveRecord::Base

  # attr_accessible :title, :content, :publish_date, :user_id, :published, :food_images_attributes, :restaurant, :restaurant_location, :rest, :recipe,
  # :recipes_attributes, :featured_blog
  
  has_many :food_images
  has_many :comments
  has_many :recipes
  belongs_to :user
  
  accepts_nested_attributes_for :food_images, :allow_destroy => true
  # accepts_nested_attributes_for :food_images, :reject_if => lambda { |g| g[:image].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :recipes, :allow_destroy => true

  # scope :featured_blogs, where(:featured_blog => true).order('publish_date DESC').limit(6)

  scope :featured_blogs, -> {
    where(:featured_blog => true).order('publish_date DESC').limit(6)
  }


  def self.featured_image(t)
    t.food_images.where(:featured => true)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_filter :authenticate_admin, :only => [:manage, :list, :create, :update, :destroy]
  # before_filter :authenticate

  def index
    @food_blogs = Food.reorder("publish_date DESC").page(params[:page]).per_page(5)
    quotes = Quote.where(:food => true).pluck(:id)
    @quote = Quote.where(:id => quotes.sample).first if Quote.where(:id => quotes.sample).first
    @featured_blogs_one = Food.featured_blogs.in_groups_of(4, false).first
    @featured_blogs_two = Food.featured_blogs.in_groups_of(4, false).last
  end
  
  def new
    @food_blog = Food.new
    1.times { @food_blog.food_images.build }
    recipe = @food_blog.recipes.build
    recipe.ingredients.build
  end
  
  def edit
    @food_blog = Food.find(params[:id])    
  end
  
  def list
    @search = Food.ransack(params[:search])
    @food_blogs = @search.result.paginate(page: params[:page], per_page: params[12])
  end
  
  def show
    @food_blog = Food.find(params[:id])
    @comment = @food_blog.comments.build
    @comments = Comment.where(:food_id => @food_blog.id).order('created_at DESC')
    @images = @food_blog.food_images
    @featured_image = @food_blog.food_images.where(:featured => true)
    @all_but_featured_image = @images - [@featured_image.first]
    if request.path != food_path(@food_blog)
      redirect_to @food_blog, status: :moved_permanently
    end
  end
  
  def create
    @food_blog = Food.new(food_params)
    @food_blog.user_id = current_user.id
    if @food_blog.save
      redirect_to(:action => 'list')
    else
      render "manage"
    end
  end
    
  def update
    @food_blog = Food.find(params[:id])
    if @food_blog.update_attributes(food_params)
      redirect_to(:action => 'list')
    else
      render "manage"
    end    
  end
  
  def destroy
    Food.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
  
  private
  
  def food_params
    params.require(:food).permit(
    :title, 
    :content, 
    :publish_date, 
    :user_id, 
    :published, 
    :restaurant, 
    :restaurant_location, 
    :rest, 
    :recipe, 
    :featured_blog,
    food_images_attributes: [:id, :image, :name, :description, :featured, :food_id],
    comments_attributes: [:id, :content, :user_id, :commenter, :gallery_id, :travel_id, :food_id],
    recipes_attributes: [:id, :name, :recipe_instructions, :food_id], ingredients_attributes: [:id, :ingredient_name, :quantity_used, :recipe_id],
    )
  end


end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food_image_fields.html.erb
<div class="row fields">
  <div class="span5">
  <%= f.input :image, :as => :file, :hint => f.template.image_tag(f.object.image.url(:thumb)) %>
  <%= f.input :name %>
  </div>
  
  <div class="span4">
  <%= f.input :featured, :as => :select %>
  <%= f.input :description %>
  </div>
  
  <div class="span1 offset2">
  </div>
</div>
<br><br>

app/views/foods/_ingredient_fields.html.erb
<div class="row fields">
  <div class="span5">
    <%= f.input :ingredient_name %>
  </div>
  <div class="span4">
    <%= f.input :quantity_used %>
  </div>
  
   
</div>

app/views/foods/_manage.html.erb
<%= simple_form_for(@food_blog, :html => {:multipart => true, :class => "form-horizontal"}) do |f| %>
  
  <%= f.association :food_images do |builder| %>
      <%= render 'food_image_fields', :f => builder %>
  <% end %>


  <br><br>


  
  <%= f.input :title, :input_html => { :class => "input-xxlarge" } %>
  <%= f.input :publish_date, :as => :date, :order => [:month, :day, :year], :start_year => 2013, :end_year => Time.now.year, :input_html => {:class => "input-small"}, :label => "Publish Date" %>
  <%= f.input :featured_blog, :as => :boolean, :label => "Featured blog?" %>
  <%= f.input :content, :label => 'Blog Content', :input_html => { style: 'height:200px;', :class => "input-xxlarge" } %>


  
  <%= f.input :rest, :as => :boolean, :label => "Restaurant ?" %>
      <div id="restaurant_details" style="display:none;">
          <%= f.input :restaurant, :input_html => { :class => "input-xxlarge" } %>
          <%= f.input :restaurant_location, :input_html => { :class => "input-xxlarge" } %>
      </div>



  <%= f.input :recipe, :as => :boolean, :label => "Recipe ?" %>
      <div id="recipe_details" style="display:none;">
          <%= f.simple_fields_for :recipes do |builder| %>
            <%= render 'recipe_fields', :f => builder %><br><br><br><br>
          <% end %>
      </div>
  
  <br> 
  
  <div class="submit-btn-pull-right">
    <div class="btn primary white-link"><%= link_to "Cancel", list_food_blogs_path %></div>
    <%= f.button :submit, :class => "primary" %>
  </div>  
<% end %>


  

<script type="text/javascript">
  var checkbox = document.getElementById('food_rest');
  var details_div = document.getElementById('restaurant_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
  
  
  var recipe_checkbox = document.getElementById('food_recipe');
  var recipe_details_div = document.getElementById('recipe_details');
  recipe_checkbox.onchange = function() {
     if(this.checked) {
       recipe_details_div.style['display'] = 'block';
     } else {
       recipe_details_div.style['display'] = 'none';
     }
  };
</script>

app/views/foods/_recipe_fields.html.erb
<div class="row fields">
<%= f.input :name, :label => "Recipe Name", :input_html => { :class => "input-xxlarge" } %>
  <%= f.simple_fields_for :ingredients do |builder| %>
    <%= render 'ingredient_fields', :f => builder %>
  <% end %>
<%= f.input :recipe_instructions, :input_html => { style: 'height:200px;', :class => "input-xxlarge" } %>          
</div>

app/views/foods/edit.html.erb
<%= render :partial => 'manage'%>

app/views/foods/index.html.erb
  <div class="promocyja-font food-quote">“<%= @quote.quote if @quote %>”<br> 
    <span style="font-size: 22px">– <%= @quote.author if @quote %></span>
  </div>

<div class="hidden-sm hidden-xs">  
<% if Food.featured_blogs.count > 0 %> 
  <%= render :partial => 'shared/blog_index_carousel', :locals => {the_model: Food}%>
<% end %>
</div>
  <br><br>

    
    <% @food_blogs.each do |fb| %>
    
      <div class="white-box">
        <div class="row col-sm-12 col-xs-12">
          <div class="col-md-3 col-sm-3 col-xs-3 travel-index-left-column">
            <%= image_tag(fb.user.image_url(:thumb), :class => "round-images") if fb.user %><br><br>

            AUTHOR:<br>
            <%= fb.user.name %><br><br>

            DATE:<br>
            <%= fb.publish_date.strftime("%B %d, %Y") %><br><br>

            <% unless fb.restaurant.empty? %>
            Restaurant:<br>
            <%= fb.restaurant %><br><br>
            <% end %>
            
            COMMENTS:<br>
            <%= pluralize(fb.comments.count, 'Comment') %><br><br>
          </div>
        
          <div class="col-md-9 col-sm-9 col-xs-9 travel-index-right-column">
            <p class="mathlete-bulky-font" style="font-size: 38px"><%= link_to fb.title, food_path(fb) %></p><br>
            <%= image_tag(Food.featured_image(fb).first.image_url(:index), class: "img-responsive")%><br><br>
            <%= truncate(fb.content, :length => 200) %>
          </div>    
        </div>
      </div><br><br>    
    <% end %>
    
  <div class="pull-right"><%= will_paginate @food_blogs, renderer: BootstrapPagination::Rails %></div>    
    

app/views/foods/list.html.erb
<h4>List of Food Blogs</h4></br>

<div class="display-inline">
  <%= link_to "«« Back to Admin »»", admins_path %>

  <div>
    <%= search_form_for @search, :url => list_food_blogs_path do |f| %>
      Keyword Search: <%= f.search_field :title_or_content_cont, :label => false %>
      SORT BY: <%= f.sort_link :id, "ID Order" %>
    <% end %>
  </div>
</div>

<br>

<div style="margin-left: -20px;">
  <% @food_blogs.each do |f| %>
  <ul class="no-margin-or-bullet list-pages-grid">
    <li class="list-pages-li">
    <%= link_to image_tag(Food.featured_image(f).first.image_url(:list)), food_path(f)  %><br>
      <div class="list-pages-text">
        <h4 style="color: #aaa"><%= f.rest? ? 'RESTAURANT': '' %> <%= f.recipe? ? 'RECIPE': '' %> </h4><hr class="dotted">
        <h4 style="color: black; margin-bottom: 12px"><%= truncate(f.title, :length => 30) %></h4>
        <p style="font-family: Helvetica Neue, font-size: 10px;"><%= truncate(f.content, :length => 100) %></p>
        <%= link_to "Edit", :action => 'edit', :id => f.id %> | <%= link_to "Delete", f, :method => :delete %>
      </div>
    </li>
  </ul>
  <% end %>
</div>


<div class="pull-right"><%= will_paginate @food_blogs, renderer: BootstrapPagination::Rails %></div>    


<div class="btn primary white-link pull-right"><%= link_to "New", :action => 'new' %></div>

app/views/foods/manage.html.erb
<%= simple_form_for(@food_blog, :html => {:multipart => true, :class => "form-horizontal"}) do |f| %>
  
  <%= f.association :food_images do |builder| %>
      <%= render 'food_image_fields', :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add Food Image", f, :food_images %></p>


  <br><br>


  
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :title, :input_html => { :class => "input-xxlarge" } %>
  <%= f.input :publish_date, :as => :date, :order => [:month, :day, :year], :start_year => 2013, :end_year => Time.now.year, :input_html => {:class => "input-small"}, :label => "Publish Date" %>
  <%= f.input :featured_blog, :as => :boolean, :label => "Featured blog?" %>
  <%= f.input :content, :label => 'Blog Content', :input_html => { style: 'height:200px;', :class => "input-xxlarge" } %>


  
  <%= f.input :rest, :as => :boolean, :label => "Restaurant ?" %>
      <div id="restaurant_details" style="display:none;">
          <%= f.input :restaurant, :input_html => { :class => "input-xxlarge" } %>
          <%= f.input :restaurant_location, :input_html => { :class => "input-xxlarge" } %>
      </div>



  <%= f.input :recipe, :as => :boolean, :label => "Recipe ?" %>
      <div id="recipe_details" style="display:none;">
          <%= f.simple_fields_for :recipes do |builder| %>
            <%= render 'recipe_fields', :f => builder %><br><br><br><br>
          <% end %>
          <p><%= link_to_add_fields "Add New Recipe", f, :recipes %></p>
      </div>
  
  <br> 
  
  <div class="submit-btn-pull-right">
    <div class="btn primary white-link"><%= link_to "Cancel", list_food_blogs_path %></div>
    <%= f.button :submit, :class => "primary" %>
  </div>  
<% end %>


  

<script type="text/javascript">
  var checkbox = document.getElementById('food_rest');
  var details_div = document.getElementById('restaurant_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
  
  
  var recipe_checkbox = document.getElementById('food_recipe');
  var recipe_details_div = document.getElementById('recipe_details');
  recipe_checkbox.onchange = function() {
     if(this.checked) {
       recipe_details_div.style['display'] = 'block';
     } else {
       recipe_details_div.style['display'] = 'none';
     }
  };
</script>

app/views/foods/new.html.erb
<%= render :partial => 'manage'%>

app/views/foods/show.html.erb
<div class="container">

  <div class="white-box">
    <div class="row">
      <div class="col-md-2 col-sm-2 col-xs-2">
        <%= food_logo %>
      </div>
      
      <%= render :partial => 'shared/show_blog_content', :locals => {blog: @food_blog}%>
    
      <% if @food_blog.recipe == true %>        
        <% @food_blog.recipes.each do |r| %>
          <div class="tape-background">
            <p class="mathlete-bulky-font span11" style="font-size: 35px;"><%= r.name %></p>
            <div class="col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-4 col-xs-offset-1">
              <p class="mathlete-bulky-font" style="font-size: 35px;">Ingredients:</p><br><br> 
              <% r.ingredients.each do |i| %> 
                  <ul class="no-margin-or-bullet">
                    <li>  
                      <%= i.quantity_used %>
                      <%= i.ingredient_name %>
                    </li>
                  </ul>              
              <% end %>
            </div>

            <div class="col-md-5 col-sm-5 col-xs-5" style="margin-left: 50px;">
              <p class="mathlete-bulky-font" style="font-size: 35px;">Recipe:</p>
              <%= r.recipe_instructions %>
            </div>
          </div>
        <% end %>
      <% end %>
      
      
    <br><br><br>
    
    <div class="row">
      <div class="col-md-12">
        <h5 class="mathlete-bulky-font" style="font-size:28px">Leave a comment</h5>
        <%= simple_form_for @comment, :url => create_food_comment_path, :method => :post, :html => {:class => 'form-horizontal'} do |f| %>  
            <%= f.input :food_id, :as => :hidden, :input_html => { :value => @food_blog.id } %>
            <%= render :partial => "shared/comment_form", :locals => {f: f} %>
          <div class="submit-btn-pull-right"><%= f.button :submit, 'Submit', :class => "primary" %></div>
        <% end %>
      </div>  
    </div>
    
        
    <div class="row">
      <%= render :partial => 'shared/show_blog_comment', :locals => {blog: @food_blog}%>
    </div>

    
    
  </div>  
</div>