config/routes.rb
Kings::Application.routes.draw do

  root :to => 'pages#home'

  match '/login', :to => 'sessions#new', :as => :login, via: [:get]
  match '/signout', :to => 'sessions#destroy', :as => :sign_out, via: [:get, :post]

  match '/galleries/index2', :to => 'galleries#index2', :as => :index2_gallery, via: [:get]
  match '/galleries/engagement', :to => 'galleries#engagement', :as => :engagement, via: [:get]
  match '/galleries/travel', :to => 'galleries#travel_images', :as => :travel_images, via: [:get]
  match '/galleries/wedding', :to => 'galleries#wedding', :as => :wedding, via: [:get]

  match '/galleries/manage', :to => 'galleries#manage', :as => :manage_gallery, via: [:get, :post]
  match '/galleries/list', :to => 'galleries#list', :as => :list_gallery, via: [:get, :post]
  post  '/galleries/wedding_photos', :to => 'comments#create_gallery_comment', :as => :create_gallery_comment, via: [:get, :post]
  post  '/travels/:id', :to => 'comments#create_travel_comment', :as => :create_travel_comment, via: [:get, :post]
  post  '/foods/:id', :to => 'comments#create_food_comment', :as => :create_food_comment, via: [:get, :post]

  match '/users/manage', :to => 'users#manage', :as => :manage_user, via: [:get, :post]
  match '/users/list', :to => 'users#list', :as => :list_user, via: [:get, :post]
  
  match '/travels/manage', :to => 'travels#manage', :as => :manage_travel, via: [:get, :post]
  match '/travels/list', :to => 'travels#list', :as => :list_travel_blogs, via: [:get, :post]

  match '/foods/manage', :to => 'foods#manage', :as => :manage_food, via: [:get, :post]
  match '/foods/list', :to => 'foods#list', :as => :list_food_blogs, via: [:get, :post]

  match '/quotes/manage', :to => 'quotes#manage', :as => :manage_quote, via: [:get, :post]
  match '/quotes/list', :to => 'quotes#list', :as => :list_quotes, via: [:get, :post]
  
  resources :galleries, :sessions, :users, :admins, :comments, :travels, :foods, :quotes
  

end

app/views/layouts/_footer.html.erb
<p>Made with <%= image_tag('kings_heart.png')%> in NYC.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Khuus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<% # Adding google analytics below %>   
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31729865-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
   
</head>
<body>
<div id="container">
  <div class="container">
  <div class="navbar">
    <div class="navbar-inner">
        <div class="container">
              <%= link_to logo, root_path %>
		
          <ul class="nav navbar-nav pull-right">
            <li class="<%= 'active' if controller.is_a?(GalleriesController) %>"  style="width: 195px;"><%= link_to galleries_path do %> <div class="ca-icon"></div><% end %><%= link_to "Photo Gallery", galleries_path %></li>
            <li class="<%= 'active' if controller.is_a?(TravelsController) %>" style="width: 180px;"><%= link_to travels_path do %> <div class="ca-icon2"></div><% end %><%= link_to "Our Travels", travels_path %></li>
            <li class="<%= 'active' if controller.is_a?(FoodsController) %>" style="width: 185px;"><%= link_to foods_path do %> <div class="ca-icon3"></div><% end %><%= link_to "Our Eats", foods_path %></li>
          </ul>
        </div>

    </div>
  </div>
  </div>
  


<% if current_user %>
  <div class="ribbon"><br><br>
   
    <span style="font-family: 'PacificoRegular'; font-size: 18px; line-height: 200%"><%= current_user.name %></span><br>
    <%= link_to "Sign Out", sign_out_path %>
      <div class="sign-out">
        <%= image_tag(current_user.image_url(:thumb), :class => "round-images")%><br>
      </div>
  </div>
<% end %>
  
  
  <div class="container">
    <%= yield %>
  </div>

</div>
  <footer>
    <br>
    <%= render partial: "layouts/footer" %>
  </footer>

</body>

</html>

app/views/layouts/gallery.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Khuus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <% # Adding google analytics below %>   
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-31729865-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
 
  
</head>
<body>
<div id="container">
  <div class="container">
  <div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <% if current_user %>
              <%= link_to logo, root_path %>
			  <% else %>
			  <%= link_to logo, root_path %>
            <% end %>
		
          <ul class="nav navbar-nav pull-right">
            <li class="<%= 'active' if controller.is_a?(GalleriesController) %>"  style="width: 195px;"><%= link_to galleries_path do %> <div class="ca-icon"></div><% end %><%= link_to "Photo Gallery", galleries_path %></li>
            <li class="<%= 'active' if controller.is_a?(TravelsController) %>" style="width: 180px;"><%= link_to travels_path do %> <div class="ca-icon2"></div><% end %><%= link_to "Our Travels", travels_path %></li>
            <li class="<%= 'active' if controller.is_a?(FoodsController) %>" style="width: 185px;"><%= link_to foods_path do %> <div class="ca-icon3"></div><% end %><%= link_to "Our Eats", foods_path %></li>
          </ul>
        </div>

    </div>
  </div>
  </div>
  
<% if current_user %>
  <div class="ribbon"><br><br>
   
    <span style="font-family: 'PacificoRegular'; font-size: 18px; line-height: 200%"><%= current_user.name %></span><br>
    <%= link_to "Sign Out", sign_out_path %>
      <div class="sign-out">
        <%= image_tag(current_user.image_url(:thumb), :class => "round-images")%><br>
      </div>
  </div>
<% end %>

  <div class="container">
    <%= yield %>
  </div>

</div>  

  <footer>
    <br>
    <%= render partial: "layouts/footer" %>
  </footer>

</body>

</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Khuus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container login-container">
    <%= yield %>
  </div>

</body>

</html>